from fastapi import HTTPException

from app.models.administrative_report import AdministrativeReport
from app.models.enums import ReportType
from app.repositories.administrative_report_repository import AdministrativeReportRepository
from app.repositories.user_repository import UserRepository
from app.schemas.administrative_report import AdministrativeReportCreateRequest, AdministrativeReportUpdateRequest


class AdministrativeReportService:
    def __init__(self, db):
        self.repo = AdministrativeReportRepository(db)
        self.user_repo = UserRepository(db)

    def _serialize(self, item):
        return {
            "id": item.id,
            "generated_by_user_id": item.generated_by_user_id,
            "report_type": item.report_type.value,
            "parameters_json": item.parameters_json,
            "generated_at": item.generated_at,
            "file_url": item.file_url,
        }

    def list_items(self):
        return [self._serialize(i) for i in self.repo.list_items()]

    def get_item(self, item_id):
        item = self.repo.get_by_id(item_id)
        if not item:
            raise HTTPException(status_code=404, detail="Administrative report not found")
        return self._serialize(item)

    def create_item(self, payload: AdministrativeReportCreateRequest):
        if not self.user_repo.get_by_id(payload.generated_by_user_id):
            raise HTTPException(status_code=404, detail="Generated by user not found")

        item = AdministrativeReport(
            generated_by_user_id=payload.generated_by_user_id,
            report_type=ReportType(payload.report_type),
            parameters_json=payload.parameters_json,
            file_url=payload.file_url,
        )
        return self._serialize(self.repo.create(item))

    def update_item(self, item_id, payload: AdministrativeReportUpdateRequest):
        item = self.repo.get_by_id(item_id)
        if not item:
            raise HTTPException(status_code=404, detail="Administrative report not found")

        data = payload.model_dump(exclude_unset=True)
        if "report_type" in data:
            item.report_type = ReportType(data["report_type"])
        if "parameters_json" in data:
            item.parameters_json = data["parameters_json"]
        if "file_url" in data:
            item.file_url = data["file_url"]

        return self._serialize(self.repo.save(item))

    def delete_item(self, item_id):
        item = self.repo.get_by_id(item_id)
        if not item:
            raise HTTPException(status_code=404, detail="Administrative report not found")
        self.repo.delete(item)
        return {"message": "Administrative report deleted successfully"}