"""add marketplace system

Revision ID: 1160505b3d4d
Revises: 8552ba5e40e1
Create Date: 2026-05-22 10:46:51.053272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1160505b3d4d'
down_revision: Union[str, Sequence[str], None] = '8552ba5e40e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_ci', sa.String(length=20), nullable=False),
    sa.Column('specialty_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('budget_min', sa.Integer(), nullable=True),
    sa.Column('budget_max', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'EXPIRED', name='request_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_ci'], ['users.ci'], name=op.f('fk_requests_client_ci_requests')),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], name=op.f('fk_requests_specialty_id_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests'))
    )
    op.create_index(op.f('ix_requests_city'), 'requests', ['city'], unique=False)
    op.create_index(op.f('ix_requests_client_ci'), 'requests', ['client_ci'], unique=False)
    op.create_index(op.f('ix_requests_specialty_id'), 'requests', ['specialty_id'], unique=False)
    op.create_index(op.f('ix_requests_status'), 'requests', ['status'], unique=False)
    op.create_index(op.f('ix_requests_zone'), 'requests', ['zone'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('professional_profile_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('proposed_price', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', 'COMPLETED', name='application_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['professional_profile_id'], ['professional_profiles.id'], name=op.f('fk_applications_professional_profile_id_applications')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_applications_request_id_applications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('request_id', 'professional_profile_id', name='uq_request_professional_application')
    )
    op.create_index(op.f('ix_applications_professional_profile_id'), 'applications', ['professional_profile_id'], unique=False)
    op.create_index(op.f('ix_applications_request_id'), 'applications', ['request_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('professional_availabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('professional_profile_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['professional_profile_id'], ['professional_profiles.id'], name=op.f('fk_professional_availabilities_professional_profile_id_professional_availabilities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professional_availabilities')),
    sa.UniqueConstraint('professional_profile_id', 'day_of_week', name='uq_professional_day')
    )
    op.create_index(op.f('ix_professional_availabilities_professional_profile_id'), 'professional_availabilities', ['professional_profile_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_ci', sa.String(length=20), nullable=False),
    sa.Column('professional_profile_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('ck_reviews_check_review_rating')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_reviews_application_id_reviews')),
    sa.ForeignKeyConstraint(['professional_profile_id'], ['professional_profiles.id'], name=op.f('fk_reviews_professional_profile_id_reviews')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_reviews_request_id_reviews')),
    sa.ForeignKeyConstraint(['reviewer_ci'], ['users.ci'], name=op.f('fk_reviews_reviewer_ci_reviews')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.create_index(op.f('ix_reviews_application_id'), 'reviews', ['application_id'], unique=False)
    op.create_index(op.f('ix_reviews_professional_profile_id'), 'reviews', ['professional_profile_id'], unique=False)
    op.create_index(op.f('ix_reviews_request_id'), 'reviews', ['request_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_ci'), 'reviews', ['reviewer_ci'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_reviewer_ci'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_request_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_professional_profile_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_application_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_professional_availabilities_professional_profile_id'), table_name='professional_availabilities')
    op.drop_table('professional_availabilities')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_request_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_professional_profile_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_requests_zone'), table_name='requests')
    op.drop_index(op.f('ix_requests_status'), table_name='requests')
    op.drop_index(op.f('ix_requests_specialty_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_client_ci'), table_name='requests')
    op.drop_index(op.f('ix_requests_city'), table_name='requests')
    op.drop_table('requests')
    # ### end Alembic commands ###
