"""initial schema

Revision ID: 66284b308e70
Revises: 
Create Date: 2026-04-10 11:13:29.743841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66284b308e70'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direcciones_usuario',
    sa.Column('id_direccion', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('departamento', sa.String(length=100), server_default=sa.text("'La Paz'"), nullable=False),
    sa.Column('ciudad', sa.String(length=100), server_default=sa.text("'La Paz'"), nullable=False),
    sa.Column('zona', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('referencia', sa.String(), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('es_principal', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('actualizado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id_direccion')
    )
    op.create_index('idx_direcciones_usuario_id_usuario', 'direcciones_usuario', ['id_usuario'], unique=False)
    op.create_index('idx_direcciones_usuario_zona', 'direcciones_usuario', ['zona'], unique=False)
    op.create_index('uq_direccion_principal_usuario', 'direcciones_usuario', ['id_usuario'], unique=True, postgresql_where=sa.text('es_principal = TRUE'))
    op.create_table('especialidades',
    sa.Column('id_especialidad', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id_especialidad'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index('idx_especialidades_codigo', 'especialidades', ['codigo'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('numero_whatsapp', sa.String(length=20), nullable=True),
    sa.Column('foto_perfil_url', sa.Text(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.Enum('masculino', 'femenino', 'otro', 'prefiero_no_decir', name='sexo_enum'), server_default=sa.text("'prefiero_no_decir'"), nullable=False),
    sa.Column('rol', sa.Enum('cliente', 'profesional', 'administrador', 'soporte', name='rol_usuario_enum'), server_default=sa.text("'cliente'"), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'suspendido', 'eliminado', 'bloqueado', name='estado_usuario_enum'), server_default=sa.text("'activo'"), nullable=False),
    sa.Column('correo_verificado_en', sa.TIMESTAMP(), nullable=True),
    sa.Column('ultimo_acceso_en', sa.TIMESTAMP(), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('token_recuperacion', sa.String(length=255), nullable=True),
    sa.Column('token_recuperacion_expira_en', sa.TIMESTAMP(), nullable=True),
    sa.Column('creado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('actualizado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('eliminado_en', sa.TIMESTAMP(), nullable=True),
    sa.CheckConstraint("position('@' in correo) > 1", name='chk_usuarios_correo_formato'),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('historial_busquedas',
    sa.Column('id_busqueda', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.Column('termino_busqueda', sa.String(length=255), nullable=True),
    sa.Column('id_especialidad', sa.UUID(), nullable=True),
    sa.Column('zona', sa.String(length=100), nullable=True),
    sa.Column('calificacion_minima', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('disponible_ahora', sa.Boolean(), nullable=True),
    sa.Column('cantidad_resultados', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('buscado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('calificacion_minima IS NULL OR (calificacion_minima >= 0 AND calificacion_minima <= 5)', name='chk_calificacion_minima'),
    sa.ForeignKeyConstraint(['id_especialidad'], ['especialidades.id_especialidad'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_busqueda')
    )
    op.create_table('notas_administrativas',
    sa.Column('id_nota', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_autor', sa.UUID(), nullable=False),
    sa.Column('entidad_relacionada', sa.String(length=100), nullable=False),
    sa.Column('id_entidad_relacionada', sa.UUID(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=False),
    sa.Column('privada', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_autor'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_nota')
    )
    op.create_table('perfiles_profesionales',
    sa.Column('id_perfil_profesional', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('anos_experiencia', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('zona_principal', sa.String(length=100), nullable=False),
    sa.Column('radio_servicio_km', sa.Numeric(precision=5, scale=2), server_default=sa.text('5.00'), nullable=True),
    sa.Column('referencia_trabajo', sa.Text(), nullable=True),
    sa.Column('documento_identidad_url', sa.Text(), nullable=True),
    sa.Column('estado_verificacion', sa.Enum('pendiente', 'en_revision', 'aprobado', 'rechazado', name='estado_verificacion_enum'), server_default=sa.text("'pendiente'"), nullable=False),
    sa.Column('verificacion_solicitada_en', sa.TIMESTAMP(), nullable=True),
    sa.Column('verificacion_resuelta_en', sa.TIMESTAMP(), nullable=True),
    sa.Column('verificado_por', sa.UUID(), nullable=True),
    sa.Column('calificacion_promedio', sa.Numeric(precision=3, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('cantidad_calificaciones', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cantidad_servicios_completados', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('disponible_ahora', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('contacto_publico_habilitado', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('actualizado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('anos_experiencia >= 0', name='chk_anos_experiencia'),
    sa.CheckConstraint('calificacion_promedio >= 0 AND calificacion_promedio <= 5', name='chk_calificacion_promedio'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verificado_por'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_perfil_profesional'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_index('idx_perfiles_profesionales_calificacion_promedio', 'perfiles_profesionales', ['calificacion_promedio'], unique=False)
    op.create_index('idx_perfiles_profesionales_disponible_ahora', 'perfiles_profesionales', ['disponible_ahora'], unique=False)
    op.create_index('idx_perfiles_profesionales_estado_verificacion', 'perfiles_profesionales', ['estado_verificacion'], unique=False)
    op.create_index('idx_perfiles_profesionales_id_usuario', 'perfiles_profesionales', ['id_usuario'], unique=False)
    op.create_index('idx_perfiles_profesionales_zona_principal', 'perfiles_profesionales', ['zona_principal'], unique=False)
    op.create_table('registros_auditoria',
    sa.Column('id_registro', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_usuario_actor', sa.UUID(), nullable=True),
    sa.Column('accion', sa.Enum('login', 'logout', 'registro', 'editar_perfil', 'crear_solicitud', 'editar_solicitud', 'eliminar_solicitud', 'postular_solicitud', 'aceptar_postulacion', 'rechazar_postulacion', 'calificar_servicio', 'subir_certificacion', 'validar_profesional', 'rechazar_profesional', 'suspender_usuario', 'activar_usuario', name='accion_auditoria_enum'), nullable=False),
    sa.Column('entidad', sa.String(length=100), nullable=False),
    sa.Column('id_entidad', sa.UUID(), nullable=True),
    sa.Column('valores_anteriores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('valores_nuevos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('direccion_ip', postgresql.INET(), nullable=True),
    sa.Column('agente_usuario', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario_actor'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_registro')
    )
    op.create_index('idx_registros_auditoria_accion', 'registros_auditoria', ['accion'], unique=False)
    op.create_index('idx_registros_auditoria_creado_en', 'registros_auditoria', ['creado_en'], unique=False)
    op.create_index('idx_registros_auditoria_entidad', 'registros_auditoria', ['entidad', 'id_entidad'], unique=False)
    op.create_index('idx_registros_auditoria_usuario_actor', 'registros_auditoria', ['id_usuario_actor'], unique=False)
    op.create_table('reportes_administrativos',
    sa.Column('id_reporte', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('generado_por', sa.UUID(), nullable=False),
    sa.Column('tipo_reporte', sa.Enum('usuarios', 'profesionales', 'solicitudes', 'calificaciones', 'especialidades', 'validaciones', 'dashboard', name='tipo_reporte_enum'), nullable=False),
    sa.Column('parametros_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('archivo_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['generado_por'], ['usuarios.id_usuario'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_reporte')
    )
    op.create_index('idx_reportes_administrativos_generado_por', 'reportes_administrativos', ['generado_por'], unique=False)
    op.create_index('idx_reportes_administrativos_tipo', 'reportes_administrativos', ['tipo_reporte'], unique=False)
    op.create_table('certificaciones',
    sa.Column('id_certificacion', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_perfil_profesional', sa.UUID(), nullable=False),
    sa.Column('tipo_documento', sa.Enum('ci', 'certificado', 'licencia', 'antecedente', 'otro', name='tipo_documento_enum'), server_default=sa.text("'certificado'"), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('institucion', sa.String(length=150), nullable=True),
    sa.Column('ano_emision', sa.Integer(), nullable=True),
    sa.Column('archivo_url', sa.Text(), nullable=False),
    sa.Column('verificada', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('verificada_por', sa.UUID(), nullable=True),
    sa.Column('verificada_en', sa.TIMESTAMP(), nullable=True),
    sa.Column('creado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('actualizado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('ano_emision IS NULL OR (ano_emision >= 1950 AND ano_emision <= EXTRACT(YEAR FROM CURRENT_DATE) + 1)', name='chk_ano_emision'),
    sa.ForeignKeyConstraint(['id_perfil_profesional'], ['perfiles_profesionales.id_perfil_profesional'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verificada_por'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_certificacion')
    )
    op.create_index('idx_certificaciones_perfil', 'certificaciones', ['id_perfil_profesional'], unique=False)
    op.create_index('idx_certificaciones_verificada', 'certificaciones', ['verificada'], unique=False)
    op.create_table('cola_validacion_profesionales',
    sa.Column('id_validacion', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_perfil_profesional', sa.UUID(), nullable=False),
    sa.Column('solicitado_por', sa.UUID(), nullable=False),
    sa.Column('asignado_a_soporte', sa.UUID(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'en_revision', 'aprobado', 'rechazado', name='estado_verificacion_enum'), server_default=sa.text("'pendiente'"), nullable=False),
    sa.Column('enviado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('revision_iniciada_en', sa.TIMESTAMP(), nullable=True),
    sa.Column('resuelto_en', sa.TIMESTAMP(), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('tiempo_espera_minutos', sa.Integer(), nullable=True),
    sa.Column('tiempo_revision_minutos', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('actualizado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('tiempo_espera_minutos IS NULL OR tiempo_espera_minutos >= 0', name='chk_tiempo_espera'),
    sa.CheckConstraint('tiempo_revision_minutos IS NULL OR tiempo_revision_minutos >= 0', name='chk_tiempo_revision'),
    sa.ForeignKeyConstraint(['asignado_a_soporte'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_perfil_profesional'], ['perfiles_profesionales.id_perfil_profesional'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solicitado_por'], ['usuarios.id_usuario'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_validacion'),
    sa.UniqueConstraint('id_perfil_profesional')
    )
    op.create_index('idx_cola_validacion_asignado_a_soporte', 'cola_validacion_profesionales', ['asignado_a_soporte'], unique=False)
    op.create_index('idx_cola_validacion_enviado_en', 'cola_validacion_profesionales', ['enviado_en'], unique=False)
    op.create_index('idx_cola_validacion_estado', 'cola_validacion_profesionales', ['estado'], unique=False)
    op.create_table('disponibilidades_profesional',
    sa.Column('id_disponibilidad', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_perfil_profesional', sa.UUID(), nullable=False),
    sa.Column('dia_semana', sa.Enum('lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo', name='dia_semana_enum'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('disponible', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('actualizado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('hora_inicio < hora_fin', name='chk_horario_disponibilidad'),
    sa.ForeignKeyConstraint(['id_perfil_profesional'], ['perfiles_profesionales.id_perfil_profesional'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_disponibilidad'),
    sa.UniqueConstraint('id_perfil_profesional', 'dia_semana', 'hora_inicio', 'hora_fin', name='uq_disponibilidad_profesional')
    )
    op.create_index('idx_disponibilidades_dia', 'disponibilidades_profesional', ['dia_semana'], unique=False)
    op.create_index('idx_disponibilidades_perfil', 'disponibilidades_profesional', ['id_perfil_profesional'], unique=False)
    op.create_table('especialidades_profesional',
    sa.Column('id_especialidad_profesional', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_perfil_profesional', sa.UUID(), nullable=False),
    sa.Column('id_especialidad', sa.UUID(), nullable=False),
    sa.Column('nivel', sa.Enum('basico', 'intermedio', 'avanzado', 'experto', name='nivel_especialidad_enum'), server_default=sa.text("'basico'"), nullable=False),
    sa.Column('anos_experiencia', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('anos_experiencia >= 0', name='chk_anos_exp_especialidad'),
    sa.ForeignKeyConstraint(['id_especialidad'], ['especialidades.id_especialidad'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_perfil_profesional'], ['perfiles_profesionales.id_perfil_profesional'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_especialidad_profesional'),
    sa.UniqueConstraint('id_perfil_profesional', 'id_especialidad', name='uq_especialidades_profesional')
    )
    op.create_index('idx_especialidades_profesional_especialidad', 'especialidades_profesional', ['id_especialidad'], unique=False)
    op.create_index('idx_especialidades_profesional_perfil', 'especialidades_profesional', ['id_perfil_profesional'], unique=False)
    op.create_table('solicitudes_servicio',
    sa.Column('id_solicitud', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_cliente', sa.UUID(), nullable=False),
    sa.Column('id_especialidad', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('departamento', sa.String(length=100), server_default=sa.text("'La Paz'"), nullable=False),
    sa.Column('ciudad', sa.String(length=100), server_default=sa.text("'La Paz'"), nullable=False),
    sa.Column('zona', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('referencia', sa.Text(), nullable=True),
    sa.Column('fecha_preferida', sa.Date(), nullable=True),
    sa.Column('hora_preferida_inicio', sa.Time(), nullable=True),
    sa.Column('hora_preferida_fin', sa.Time(), nullable=True),
    sa.Column('presupuesto_minimo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('presupuesto_maximo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('abierta', 'en_proceso', 'asignada', 'completada', 'cancelada', name='estado_solicitud_enum'), server_default=sa.text("'abierta'"), nullable=False),
    sa.Column('id_profesional_asignado', sa.UUID(), nullable=True),
    sa.Column('canal_contacto', sa.Enum('whatsapp', 'telefono', 'chat_interno', 'otro', name='canal_contacto_enum'), server_default=sa.text("'whatsapp'"), nullable=False),
    sa.Column('activa', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('actualizado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('cerrado_en', sa.TIMESTAMP(), nullable=True),
    sa.CheckConstraint('\n            (\n                hora_preferida_inicio IS NULL AND hora_preferida_fin IS NULL\n            ) OR (\n                hora_preferida_inicio IS NOT NULL AND hora_preferida_fin IS NOT NULL\n                AND hora_preferida_inicio < hora_preferida_fin\n            )\n            ', name='chk_horario_preferido'),
    sa.CheckConstraint('\n            (\n                presupuesto_minimo IS NULL AND presupuesto_maximo IS NULL\n            ) OR (\n                presupuesto_minimo IS NOT NULL AND presupuesto_maximo IS NOT NULL\n                AND presupuesto_minimo >= 0\n                AND presupuesto_maximo >= presupuesto_minimo\n            )\n            ', name='chk_presupuesto_solicitud'),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuarios.id_usuario'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_especialidad'], ['especialidades.id_especialidad'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_profesional_asignado'], ['perfiles_profesionales.id_perfil_profesional'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_solicitud')
    )
    op.create_index('idx_solicitudes_cliente', 'solicitudes_servicio', ['id_cliente'], unique=False)
    op.create_index('idx_solicitudes_creado_en', 'solicitudes_servicio', ['creado_en'], unique=False)
    op.create_index('idx_solicitudes_especialidad', 'solicitudes_servicio', ['id_especialidad'], unique=False)
    op.create_index('idx_solicitudes_estado', 'solicitudes_servicio', ['estado'], unique=False)
    op.create_index('idx_solicitudes_profesional_asignado', 'solicitudes_servicio', ['id_profesional_asignado'], unique=False)
    op.create_index('idx_solicitudes_zona', 'solicitudes_servicio', ['zona'], unique=False)
    op.create_table('zonas_profesional',
    sa.Column('id_zona_profesional', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_perfil_profesional', sa.UUID(), nullable=False),
    sa.Column('departamento', sa.String(length=100), server_default=sa.text("'La Paz'"), nullable=False),
    sa.Column('ciudad', sa.String(length=100), server_default=sa.text("'La Paz'"), nullable=False),
    sa.Column('zona', sa.String(length=100), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_perfil_profesional'], ['perfiles_profesionales.id_perfil_profesional'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_zona_profesional'),
    sa.UniqueConstraint('id_perfil_profesional', 'departamento', 'ciudad', 'zona', name='uq_zona_profesional')
    )
    op.create_index('idx_zonas_profesional_perfil', 'zonas_profesional', ['id_perfil_profesional'], unique=False)
    op.create_index('idx_zonas_profesional_zona', 'zonas_profesional', ['zona'], unique=False)
    op.create_table('calificaciones_servicio',
    sa.Column('id_calificacion', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_solicitud', sa.UUID(), nullable=False),
    sa.Column('id_cliente', sa.UUID(), nullable=False),
    sa.Column('id_perfil_profesional', sa.UUID(), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('verificada', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('actualizado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('puntuacion BETWEEN 1 AND 5', name='chk_puntuacion'),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuarios.id_usuario'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_perfil_profesional'], ['perfiles_profesionales.id_perfil_profesional'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitudes_servicio.id_solicitud'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_calificacion'),
    sa.UniqueConstraint('id_solicitud')
    )
    op.create_index('idx_calificaciones_cliente', 'calificaciones_servicio', ['id_cliente'], unique=False)
    op.create_index('idx_calificaciones_profesional', 'calificaciones_servicio', ['id_perfil_profesional'], unique=False)
    op.create_index('idx_calificaciones_puntuacion', 'calificaciones_servicio', ['puntuacion'], unique=False)
    op.create_table('postulaciones_solicitud',
    sa.Column('id_postulacion', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_solicitud', sa.UUID(), nullable=False),
    sa.Column('id_perfil_profesional', sa.UUID(), nullable=False),
    sa.Column('mensaje_propuesta', sa.Text(), nullable=True),
    sa.Column('precio_estimado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'aceptada', 'rechazada', 'cancelada', name='estado_postulacion_enum'), server_default=sa.text("'pendiente'"), nullable=False),
    sa.Column('postulado_en', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('respondido_en', sa.TIMESTAMP(), nullable=True),
    sa.Column('cancelado_en', sa.TIMESTAMP(), nullable=True),
    sa.CheckConstraint('precio_estimado IS NULL OR precio_estimado >= 0', name='chk_precio_estimado'),
    sa.ForeignKeyConstraint(['id_perfil_profesional'], ['perfiles_profesionales.id_perfil_profesional'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitudes_servicio.id_solicitud'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_postulacion'),
    sa.UniqueConstraint('id_solicitud', 'id_perfil_profesional', name='uq_postulacion_solicitud_profesional')
    )
    op.create_index('idx_postulaciones_estado', 'postulaciones_solicitud', ['estado'], unique=False)
    op.create_index('idx_postulaciones_profesional', 'postulaciones_solicitud', ['id_perfil_profesional'], unique=False)
    op.create_index('idx_postulaciones_solicitud', 'postulaciones_solicitud', ['id_solicitud'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_postulaciones_solicitud', table_name='postulaciones_solicitud')
    op.drop_index('idx_postulaciones_profesional', table_name='postulaciones_solicitud')
    op.drop_index('idx_postulaciones_estado', table_name='postulaciones_solicitud')
    op.drop_table('postulaciones_solicitud')
    op.drop_index('idx_calificaciones_puntuacion', table_name='calificaciones_servicio')
    op.drop_index('idx_calificaciones_profesional', table_name='calificaciones_servicio')
    op.drop_index('idx_calificaciones_cliente', table_name='calificaciones_servicio')
    op.drop_table('calificaciones_servicio')
    op.drop_index('idx_zonas_profesional_zona', table_name='zonas_profesional')
    op.drop_index('idx_zonas_profesional_perfil', table_name='zonas_profesional')
    op.drop_table('zonas_profesional')
    op.drop_index('idx_solicitudes_zona', table_name='solicitudes_servicio')
    op.drop_index('idx_solicitudes_profesional_asignado', table_name='solicitudes_servicio')
    op.drop_index('idx_solicitudes_estado', table_name='solicitudes_servicio')
    op.drop_index('idx_solicitudes_especialidad', table_name='solicitudes_servicio')
    op.drop_index('idx_solicitudes_creado_en', table_name='solicitudes_servicio')
    op.drop_index('idx_solicitudes_cliente', table_name='solicitudes_servicio')
    op.drop_table('solicitudes_servicio')
    op.drop_index('idx_especialidades_profesional_perfil', table_name='especialidades_profesional')
    op.drop_index('idx_especialidades_profesional_especialidad', table_name='especialidades_profesional')
    op.drop_table('especialidades_profesional')
    op.drop_index('idx_disponibilidades_perfil', table_name='disponibilidades_profesional')
    op.drop_index('idx_disponibilidades_dia', table_name='disponibilidades_profesional')
    op.drop_table('disponibilidades_profesional')
    op.drop_index('idx_cola_validacion_estado', table_name='cola_validacion_profesionales')
    op.drop_index('idx_cola_validacion_enviado_en', table_name='cola_validacion_profesionales')
    op.drop_index('idx_cola_validacion_asignado_a_soporte', table_name='cola_validacion_profesionales')
    op.drop_table('cola_validacion_profesionales')
    op.drop_index('idx_certificaciones_verificada', table_name='certificaciones')
    op.drop_index('idx_certificaciones_perfil', table_name='certificaciones')
    op.drop_table('certificaciones')
    op.drop_index('idx_reportes_administrativos_tipo', table_name='reportes_administrativos')
    op.drop_index('idx_reportes_administrativos_generado_por', table_name='reportes_administrativos')
    op.drop_table('reportes_administrativos')
    op.drop_index('idx_registros_auditoria_usuario_actor', table_name='registros_auditoria')
    op.drop_index('idx_registros_auditoria_entidad', table_name='registros_auditoria')
    op.drop_index('idx_registros_auditoria_creado_en', table_name='registros_auditoria')
    op.drop_index('idx_registros_auditoria_accion', table_name='registros_auditoria')
    op.drop_table('registros_auditoria')
    op.drop_index('idx_perfiles_profesionales_zona_principal', table_name='perfiles_profesionales')
    op.drop_index('idx_perfiles_profesionales_id_usuario', table_name='perfiles_profesionales')
    op.drop_index('idx_perfiles_profesionales_estado_verificacion', table_name='perfiles_profesionales')
    op.drop_index('idx_perfiles_profesionales_disponible_ahora', table_name='perfiles_profesionales')
    op.drop_index('idx_perfiles_profesionales_calificacion_promedio', table_name='perfiles_profesionales')
    op.drop_table('perfiles_profesionales')
    op.drop_table('notas_administrativas')
    op.drop_table('historial_busquedas')
    op.drop_table('usuarios')
    op.drop_index('idx_especialidades_codigo', table_name='especialidades')
    op.drop_table('especialidades')
    op.drop_index('uq_direccion_principal_usuario', table_name='direcciones_usuario', postgresql_where=sa.text('es_principal = TRUE'))
    op.drop_index('idx_direcciones_usuario_zona', table_name='direcciones_usuario')
    op.drop_index('idx_direcciones_usuario_id_usuario', table_name='direcciones_usuario')
    op.drop_table('direcciones_usuario')
    # ### end Alembic commands ###
