"""add verification system

Revision ID: 8552ba5e40e1
Revises: 313fa34836f3
Create Date: 2026-05-22 10:42:56.888193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8552ba5e40e1'
down_revision: Union[str, Sequence[str], None] = '313fa34836f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specialties'))
    )
    op.create_index(op.f('ix_specialties_name'), 'specialties', ['name'], unique=True)
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_ci', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_ci'], ['users.ci'], name=op.f('fk_files_uploaded_by_ci_files')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files')),
    sa.UniqueConstraint('stored_filename', name=op.f('uq_files_stored_filename'))
    )
    op.create_index(op.f('ix_files_uploaded_by_ci'), 'files', ['uploaded_by_ci'], unique=False)
    op.create_table('professional_specialties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('professional_profile_id', sa.UUID(), nullable=False),
    sa.Column('specialty_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['professional_profile_id'], ['professional_profiles.id'], name=op.f('fk_professional_specialties_professional_profile_id_professional_specialties')),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], name=op.f('fk_professional_specialties_specialty_id_professional_specialties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professional_specialties')),
    sa.UniqueConstraint('professional_profile_id', 'specialty_id', name='uq_professional_specialty')
    )
    op.create_index(op.f('ix_professional_specialties_professional_profile_id'), 'professional_specialties', ['professional_profile_id'], unique=False)
    op.create_index(op.f('ix_professional_specialties_specialty_id'), 'professional_specialties', ['specialty_id'], unique=False)
    op.create_table('verification_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('professional_profile_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='verification_request_status_enum'), nullable=False),
    sa.Column('rejection_reason', sa.String(length=1000), nullable=True),
    sa.Column('reviewed_by_ci', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['professional_profile_id'], ['professional_profiles.id'], name=op.f('fk_verification_requests_professional_profile_id_verification_requests')),
    sa.ForeignKeyConstraint(['reviewed_by_ci'], ['users.ci'], name=op.f('fk_verification_requests_reviewed_by_ci_verification_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_requests'))
    )
    op.create_index(op.f('ix_verification_requests_professional_profile_id'), 'verification_requests', ['professional_profile_id'], unique=False)
    op.create_index(op.f('ix_verification_requests_status'), 'verification_requests', ['status'], unique=False)
    op.create_table('verification_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verification_request_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('document_type', postgresql.ENUM('ID_CARD_FRONT', 'ID_CARD_BACK', 'SELFIE', 'CERTIFICATE', 'PDF_CERTIFICATION', name='verification_document_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_verification_documents_file_id_verification_documents')),
    sa.ForeignKeyConstraint(['verification_request_id'], ['verification_requests.id'], name=op.f('fk_verification_documents_verification_request_id_verification_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_documents'))
    )
    op.create_index(op.f('ix_verification_documents_file_id'), 'verification_documents', ['file_id'], unique=False)
    op.create_index(op.f('ix_verification_documents_verification_request_id'), 'verification_documents', ['verification_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_documents_verification_request_id'), table_name='verification_documents')
    op.drop_index(op.f('ix_verification_documents_file_id'), table_name='verification_documents')
    op.drop_table('verification_documents')
    op.drop_index(op.f('ix_verification_requests_status'), table_name='verification_requests')
    op.drop_index(op.f('ix_verification_requests_professional_profile_id'), table_name='verification_requests')
    op.drop_table('verification_requests')
    op.drop_index(op.f('ix_professional_specialties_specialty_id'), table_name='professional_specialties')
    op.drop_index(op.f('ix_professional_specialties_professional_profile_id'), table_name='professional_specialties')
    op.drop_table('professional_specialties')
    op.drop_index(op.f('ix_files_uploaded_by_ci'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_specialties_name'), table_name='specialties')
    op.drop_table('specialties')
    # ### end Alembic commands ###
