"""add_2fa_fields

Revision ID: 86abe44f3a2a
Revises: 4b785ad202ea
Create Date: 2026-06-19 09:15:10.666475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86abe44f3a2a'
down_revision: Union[str, Sequence[str], None] = '4b785ad202ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_professional_requests_pending_per_user'), table_name='professional_requests', postgresql_where="((status = 'PENDING'::professional_request_status_enum) AND (deleted_at IS NULL))")
    op.create_index(op.f('ix_reviews_reviewed_user_ci'), 'reviews', ['reviewed_user_ci'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_ci'), 'reviews', ['reviewer_ci'], unique=False)
    
    # --- CORRECCIÓN AQUÍ: Se añadió server_default='false' ---
    op.add_column('users', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('totp_pending_verification', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_pending_verification')
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret')
    op.drop_index(op.f('ix_reviews_reviewer_ci'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewed_user_ci'), table_name='reviews')
    op.create_index(op.f('uq_professional_requests_pending_per_user'), 'professional_requests', ['user_ci'], unique=True, postgresql_where="((status = 'PENDING'::professional_request_status_enum) AND (deleted_at IS NULL))")
    # ### end Alembic commands ###